// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using adapters.Driven.Persistence.Data;

#nullable disable

namespace adapters.Driven.Persistence.Data.Migrations
{
    [DbContext(typeof(ShcDbContext))]
    [Migration("20260605180933_AddAuthorizationSystem")]
    partial class AddAuthorizationSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.AI.AIFileInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetectedLanguage")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FileItemId")
                        .IsUnique();

                    b.ToTable("AIFileInsight");
                });

            modelBuilder.Entity("Domain.Entities.AI.AISuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FileItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedValue")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FileItemId");

                    b.HasIndex("UserId");

                    b.ToTable("AISuggestion");
                });

            modelBuilder.Entity("Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Auth.UserCredential", b =>
                {
                    b.Property<Guid>("UserCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserCredentialId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("PermissionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuthorizationPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Read file metadata and content.",
                            Name = "File.Read"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Description = "Upload files.",
                            Name = "File.Upload"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Description = "Delete files.",
                            Name = "File.Delete"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Description = "Share files.",
                            Name = "File.Share"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Description = "Create folders.",
                            Name = "Folder.Create"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Description = "Delete folders.",
                            Name = "Folder.Delete"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Description = "Share folders.",
                            Name = "Folder.Share"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Description = "Register storage nodes.",
                            Name = "Node.Register"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Description = "Manage storage nodes.",
                            Name = "Node.Manage"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Description = "Manage users.",
                            Name = "User.Manage"
                        },
                        new
                        {
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000011"),
                            Description = "Administer system settings.",
                            Name = "System.Admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("Domain.Entities.FileStorage.FileItem", b =>
                {
                    b.Property<Guid>("FileItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("StorageNodeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("FileItemId");

                    b.HasIndex("FolderId");

                    b.HasIndex("StorageNodeId");

                    b.HasIndex("UserId");

                    b.ToTable("FileItems");
                });

            modelBuilder.Entity("Domain.Entities.FileStorage.Folder", b =>
                {
                    b.Property<Guid>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("FolderId");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("UserId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Domain.Entities.LinkSharing.SharedLink", b =>
                {
                    b.Property<Guid>("SharedLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AllowDownload")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<string>("TokenUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("SharedLinkId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedLinks");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProviderInvoiceId")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("PurchaseId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.Purchase", b =>
                {
                    b.Property<Guid>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("PurchaseId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("SubscriptionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BillingInterval")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("MaxFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("StorageLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SubscriptionPlanId");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.UserSubscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserSubscriptionId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "SubscriptionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full platform administrator.",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default cloud user.",
                            Name = "User"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Storage node owner and operator.",
                            Name = "StorageNodeOwner"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Roles.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Settings.SystemSetting", b =>
                {
                    b.Property<Guid>("SystemSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AllowPublicLinkSharing")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AllowedFileExtensions")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DefaultLinkExpirationInDays")
                        .HasColumnType("int");

                    b.Property<long>("DefaultUserStorageQuotaInBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnforceLinkPasswordProtection")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("MaxFileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPasswordLength")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationMode")
                        .HasColumnType("int");

                    b.Property<bool>("RequireNumberPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequireSpecialCharacterPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequireUppercasePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TrashRetentionInDays")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorAuthRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SystemSettingId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Domain.Entities.StorageNodes.StorageNode", b =>
                {
                    b.Property<Guid>("StorageNodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TotalCapacityBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UsedCapacityBytes")
                        .HasColumnType("bigint");

                    b.HasKey("StorageNodeId");

                    b.ToTable("StorageNodes");
                });

            modelBuilder.Entity("Domain.Entities.Trash.TrashedItem", b =>
                {
                    b.Property<Guid>("TrashedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("OriginalItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OriginalParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OriginalPath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("TrashedItemId");

                    b.HasIndex("UserId");

                    b.ToTable("TrashedItems");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Users.UserSetting", b =>
                {
                    b.Property<Guid>("UserSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserSettingId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TriggeredById")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("NotificationId");

                    b.HasIndex("FileId");

                    b.HasIndex("FolderId");

                    b.HasIndex("TriggeredById");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SHC.Domain.Entities.Permissions.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubjectId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SHC.Domain.Entities.Permissions.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GrantedBySubjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("GrantedBySubjectType")
                        .HasColumnType("int");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Domain.Entities.AI.AIFileInsight", b =>
                {
                    b.HasOne("Domain.Entities.FileStorage.FileItem", "FileItem")
                        .WithOne("AIFileInsight")
                        .HasForeignKey("Domain.Entities.AI.AIFileInsight", "FileItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileItem");
                });

            modelBuilder.Entity("Domain.Entities.AI.AISuggestion", b =>
                {
                    b.HasOne("Domain.Entities.FileStorage.FileItem", "FileItem")
                        .WithMany("AISuggestions")
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Auth.UserCredential", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne("UserCredentials")
                        .HasForeignKey("Domain.Entities.Auth.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Authorization.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.FileStorage.FileItem", b =>
                {
                    b.HasOne("Domain.Entities.FileStorage.Folder", "Folder")
                        .WithMany("FileItems")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.StorageNodes.StorageNode", "StorageNode")
                        .WithMany("FileItems")
                        .HasForeignKey("StorageNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("StorageNode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.FileStorage.Folder", b =>
                {
                    b.HasOne("Domain.Entities.FileStorage.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentFolder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.LinkSharing.SharedLink", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.Purchases.Purchase", "Purchase")
                        .WithOne("Invoice")
                        .HasForeignKey("Domain.Entities.Purchases.Invoice", "PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.Purchase", b =>
                {
                    b.HasOne("Domain.Entities.Purchases.Subscription", "Subscription")
                        .WithMany("Purchases")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.Subscription", b =>
                {
                    b.HasOne("Domain.Entities.Purchases.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.UserSubscription", b =>
                {
                    b.HasOne("Domain.Entities.Purchases.Subscription", "Subscription")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Roles.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Trash.TrashedItem", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Users.UserSetting", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("Domain.Entities.Users.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Entities.Users.Settings.NotificationSetting", "NotificationSettings", b1 =>
                        {
                            b1.Property<Guid>("UserSettingId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("EmailNotifications")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("FileShared")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("InAppNotifications")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("PushNotifications")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("SmsNotifications")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("StorageLow")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("UserSettingId");

                            b1.ToTable("UserSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingId");
                        });

                    b.OwnsOne("Domain.Entities.Users.Settings.PrivacySetting", "PrivacySettings", b1 =>
                        {
                            b1.Property<Guid>("UserSettingId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("AllowLinkDownload")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("AllowSearchEngineIndexing")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("ShowActivityStatus")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("ShowProfilePicture")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("ShowRecentlyUsedFiles")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("UserSettingId");

                            b1.ToTable("UserSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingId");
                        });

                    b.OwnsOne("Domain.Entities.Users.Settings.StorageSetting", "StorageSettings", b1 =>
                        {
                            b1.Property<Guid>("UserSettingId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("AutoRenameDuplicates")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("AutoSyncEnabled")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("ChunkSizeKB")
                                .HasColumnType("int");

                            b1.Property<string>("ConflictResolutionStrategy")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<bool>("EnableCompression")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("EnableVersioning")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("MaxConcurrentDownloads")
                                .HasColumnType("int");

                            b1.Property<int>("MaxConcurrentUploads")
                                .HasColumnType("int");

                            b1.Property<bool>("PreferFastUploads")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("ResumeInterruptedUploads")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("SyncIntervalSeconds")
                                .HasColumnType("int");

                            b1.Property<bool>("SyncOnlyOnWiFi")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("UploadInChunks")
                                .HasColumnType("tinyint(1)");

                            b1.Property<string>("UploadStrategy")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("UserSettingId");

                            b1.ToTable("UserSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingId");
                        });

                    b.OwnsOne("Domain.Entities.Users.Settings.UiSetting", "UiSettings", b1 =>
                        {
                            b1.Property<Guid>("UserSettingId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("DefaultView")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<bool>("ShowHiddenFiles")
                                .HasColumnType("tinyint(1)");

                            b1.Property<string>("SortBy")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("UserSettingId");

                            b1.ToTable("UserSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingId");
                        });

                    b.Navigation("NotificationSettings")
                        .IsRequired();

                    b.Navigation("PrivacySettings")
                        .IsRequired();

                    b.Navigation("StorageSettings")
                        .IsRequired();

                    b.Navigation("UiSettings")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("Domain.Entities.FileStorage.FileItem", "FileItems")
                        .WithMany("Notifications")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.FileStorage.Folder", "Folder")
                        .WithMany("Notifications")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Users.User", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredById");

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileItems");

                    b.Navigation("Folder");

                    b.Navigation("TriggeredBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.FileStorage.FileItem", b =>
                {
                    b.Navigation("AIFileInsight");

                    b.Navigation("AISuggestions");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.FileStorage.Folder", b =>
                {
                    b.Navigation("FileItems");

                    b.Navigation("Notifications");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.Purchase", b =>
                {
                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.Subscription", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Purchases.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.StorageNodes.StorageNode", b =>
                {
                    b.Navigation("FileItems");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Navigation("UserCredentials")
                        .IsRequired();

                    b.Navigation("UserSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
